puts
puts "Welcome to the Cow and Bull Simulator!"
puts "<with 4 letters, all arrangements>"
puts "<Plus a counter!>"
puts

print "Would you like to read the rules?(Yes/No): "
rules=gets.chomp.downcase
counter=1

if rules=="yes" || rules=="no"
	 if rules== "yes"
		 puts
		 puts "A random four letter word will be generated by the computer."
		 puts "You, as the player, will make guesses about this word using various four letter words to obtain clues about the final word."
		 puts "A cow means that a letter that you have in your guess is in the goal word, but is NOT in its right place."
		 puts "A bull means that a letter that you have in your guess is in the goal word AND is in its right place."
		 puts
		 print "Are you ready?(Yes/No): "
		 ready=gets.chomp.downcase
	 else rules== "no"
		 puts
		 print "Alrighty, hotshot. You game?(Yes/No): "
		 ready=gets.chomp.downcase
	 end
end

if ready=="yes" || ready=="no"
	 if ready== "no"
		 puts
		 puts "Alright...come back when you are!"
		 puts
	 else ready== "yes"
		 puts
		 puts "Let the game begin!"
	 	 alpha_array= ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
		 char1= alpha_array.sample
		 char2= alpha_array.sample
		 while char2==char1
			 char2=alpha_array.sample
		 end
		 char3= alpha_array.sample
		 while (char3==char1)||(char3==char2)
			 char3=alpha_array.sample
		 end
		 char4= alpha_array.sample
		 while (char4==char1)||(char4==char2)||(char4==char3)
			 char4=alpha_array.sample
		 end
		 goal=char1.to_s+char2.to_s+char3.to_s+char4.to_s
	 
		 #puts goal
		 puts "The goal word has been generated!"
		 print "What is your guess?: " 
		 guess= gets.chomp.downcase
	 	 lengthcheck= guess.length != 4
		 charcheck= (guess[0]==guess[1])||(guess[0]==guess[2])||(guess[0]==guess[3])||(guess[1]==guess[2])||(guess[1]==guess[3])||(guess[2]==guess[3])

		 while lengthcheck==true || charcheck==true
			 puts "Hey! Only words with four distinct letters are allowed!"
			 print "What is your guess?: " 
			 guess= gets.chomp.downcase
			 lengthcheck= guess.length != 4
			 charcheck= (guess[0]==guess[1])||(guess[0]==guess[2])||(guess[0]==guess[3])||(guess[1]==guess[2])||(guess[1]==guess[3])||(guess[2]==guess[3])
		 end
	 
		 while guess != goal
			 bulls= 0
			 cows= 0
			 for a in 0..3
				 if goal[a]==guess[a]
					 bulls+=1
				 end
				 if a==0
					 if goal[a]==guess[1]||goal[a]==guess[2]||goal[a]==guess[3]
						 cows+=1
					 end
				 elsif a==1
					 if goal[a]==guess[0]||goal[a]==guess[2]||goal[a]==guess[3]
						 cows+=1
					 end
				 elsif a==2
					 if goal[a]==guess[0]||goal[a]==guess[1]||goal[a]==guess[3]
						 cows+=1
					 end
				 elsif a==3
					 if goal[a]==guess[0]||goal[a]==guess[1]||goal[a]==guess[2]
						 cows+=1
					 end
				 end
			 end
			 counter+=1
			 puts
			 puts("#{guess.to_s} has #{bulls.to_s} bull(s) and #{cows.to_s} cow(s).")
			 puts
			 print "What is your guess?: " 
			 guess= gets.chomp.downcase
			 lengthcheck= guess.length != 4
			 charcheck= (guess[0]==guess[1])||(guess[0]==guess[2])||(guess[0]==guess[3])||(guess[1]==guess[2])||(guess[1]==guess[3])||(guess[2]==guess[3])
			 while lengthcheck==true || charcheck==true
				puts "Hey! Only words with four distinct letters are allowed!"
				 print "What is your guess?: " 
				 guess= gets.chomp.downcase
				 lengthcheck= guess.length != 4
				 charcheck= (guess[0]==guess[1])||(guess[0]==guess[2])||(guess[0]==guess[3])||(guess[1]==guess[2])||(guess[1]==guess[3])||(guess[2]==guess[3])
			 end
		 end
		 puts
	 puts "You've cracked it!!!"
	 puts("You took #{counter.to_s} guesses!")
	 puts "Thanks for playing!"
	 end
 end