def hearrules(x)
	 if x== "yes"
		 puts
		 puts "A random four letter word will be generated by the computer."
		 puts "You, as the player, will make guesses about this word using various four letter words to obtain clues about the final word."
		 puts "A cow means that a letter that you have in your guess is in the final word, but is NOT in its right place."
		 puts "A bull means that a letter that you have in your guess is in the final word AND is in its right place."
		 puts
		 print "Are you ready?(Yes/No): " 
	 else x== "no"
		 puts
		 print "Alrighty, hotshot. You game?(Yes/No): "
	 end
end

def thegame
	 alpha_array= ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
	 char1= alpha_array.sample
	 char2= alpha_array.sample
	 while char2==char1
		 char2=alpha_array.sample
	 end
	 char3= alpha_array.sample
	 while (char3==char1)||(char3==char2)
		 char3=alpha_array.sample
	 end
	 char4= alpha_array.sample
	 while (char4==char1)||(char4==char2)||(char4==char3)
		 char4=alpha_array.sample
	 end
	 goal=char1.to_s+char2.to_s+char3.to_s+char4.to_s

	 #puts goal
	 puts "The word has been generated!"
	 print "What is your guess?: " 
	 guess= gets.chomp.downcase

	 def guess_process(goal, guess)
		 lengthcheck= guess.length != 4
		 charcheck= (guess[0]==guess[1])||(guess[0]==guess[2])||(guess[0]==guess[3])||(guess[1]==guess[2])||(guess[1]==guess[3])||(guess[2]==guess[3])

		 while lengthcheck==true || charcheck==true
			 puts "Hey! Only words with four distinct letters are allowed!"
			 print "What is your guess?: " 
			 guess= gets.chomp.downcase
			 lengthcheck= guess.length != 4
			 charcheck= (guess[0]==guess[1])||(guess[0]==guess[2])||(guess[0]==guess[3])||(guess[1]==guess[2])||(guess[1]==guess[3])||(guess[2]==guess[3])
		 end

		 while guess != goal
			 def cnbsys(goal, guess)
				 bulls= 0
				 cows= 0
				 for a in 0..3
					 if goal[a]==guess[a]
						 bulls+=1
					 end
					 if a==0
						 if goal[a]==guess[1]||goal[a]==guess[2]||goal[a]==guess[3]
							 cows+=1
						 end
					 elsif a==1
						 if goal[a]==guess[0]||goal[a]==guess[2]||goal[a]==guess[3]
							 cows+=1
						 end
					 elsif a==2
						 if goal[a]==guess[0]||goal[a]==guess[1]||goal[a]==guess[3]
							 cows+=1
						 end
					 elsif a==3
						 if goal[a]==guess[0]||goal[a]==guess[1]||goal[a]==guess[2]
							 cows+=1
						 end
					 end
				 end
				 puts
				 puts guess.to_s+" has "+bulls.to_s+" bull(s)"+" and "+cows.to_s+" cow(s)."
				 puts
			 end
			 cnbsys(goal, guess)
			 print "What is your guess?: " 
			 guess= gets.chomp.downcase
			 lengthcheck= guess.length != 4
			 charcheck= (guess[0]==guess[1])||(guess[0]==guess[2])||(guess[0]==guess[3])||(guess[1]==guess[2])||(guess[1]==guess[3])||(guess[2]==guess[3])
			 while lengthcheck==true || charcheck==true
				 puts "Hey! Only words with four distinct letters are allowed!"
				 print "What is your guess?: " 
				 guess= gets.chomp.downcase
				 lengthcheck= guess.length != 4
				 charcheck= (guess[0]==guess[1])||(guess[0]==guess[2])||(guess[0]==guess[3])||(guess[1]==guess[2])||(guess[1]==guess[3])||(guess[2]==guess[3])
			 end
		 end
		 puts
		 puts "You've cracked it!!!"
		 puts "Thanks for playing!"
	 end
	 guess_process(goal, guess)
end


def gamestart(x)
	 if x== "yes"
		 puts
		 puts "Let the game begin!"
		 puts
		 thegame
	 else x== "no"
		 puts
		 puts "Alright...come back when you are!"
	 end	 
end

puts "Welcome to the Cow and Bull Simulator!"
puts "<with 4 letters, all arrangements>"
puts

print "Would you like to hear the rules?(Yes/No): "
rules=gets.chomp.downcase
if rules=="yes" || rules=="no"
	 hearrules(rules)
else
	 puts
	 puts "Um...either a Yes or a No please."
	 rules=gets.chomp.downcase
	 if rules=="yes" || rules=="no"
		 hearrules(rules)
	 else
		 puts
		 puts "Um...either a Yes or a No please. Come on now..."
		 rules=gets.chomp.downcase
		 hearrules(rules)
	 end
end

ready=gets.chomp.downcase
if ready=="yes" || ready=="no"
	 gamestart(ready)
else
	 puts
	 puts "Um...either a Yes or a No please."
	 ready=gets.chomp.downcase
	 if ready=="yes" || ready=="no"
		 gamestart(ready)
	 else
		 puts
		 puts "Um...either a Yes or a No please. Come on now..."
		 ready=gets.chomp.downcase
		 gamestart(ready)
	 end
end

#YES I KNOW I COULD HAVE USED WHILE LOOPS.
#I THOUGHT ABOUT THAT AFTER THE FACT, OKAY?